name: Update Release on Main Push

on:
  push:
    branches:
      - stage

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag name
        id: get_latest_tag
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"
      - name: Generate Changelog
        id: generate_changelog
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commits } = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
            });
            const messages = commits.map((commit) => commit.commit.message);
            const changelog = messages.join("\n");
            return {
              changelog,
            };
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.tag_name }}
          release_name: Release ${{ steps.get_latest_tag.outputs.tag_name }}
          body: |
            ## Changelog
            ${{ steps.generate_changelog.outputs.changelog }}