name: Create Release on Main Push

on:
  push:
    branches:
      - stage

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag name
        id: get_latest_tag
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"
      - name: Bump version
        id: bump_version
        run: echo "::set-output name=new_tag_name::$(./bump_version.sh ${{ steps.get_latest_tag.outputs.tag_name }})"
        shell: bash
      - name: Generate Changelog
        id: generate_changelog
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commits } = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
            });
            const messages = commits.map((commit) => commit.commit.message);
            const changelog = messages.join("\n");
            return {
              changelog,
            };
      - name: Create Release
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { data: release } = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ steps.bump_version.outputs.new_tag_name }}",
              name: "Release Mark ${{ steps.bump_version.outputs.new_tag_name }}",
              body: `## Changelog\n\n${{ steps.generate_changelog.outputs.changelog }}`,
              draft: false,
              prerelease: false,
            });
